[features]
seeds = false 
[programs.localnet]
solscatter = "2DGGNTArZZCY9P1JaAuPn548fWe9hRTM92BgVF8bJgyS"

[programs.devnet]
solscatter = "2DGGNTArZZCY9P1JaAuPn548fWe9hRTM92BgVF8bJgyS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/ksuphawit/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
