[features]
seeds = false 
[programs.localnet]
solscatter = "BzxshYSrD3KdLeQHMpXFPdgtfcwUUky5jeBefFbYqrxd"

[programs.devnet]
solscatter = "BzxshYSrD3KdLeQHMpXFPdgtfcwUUky5jeBefFbYqrxd"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/ksuphawit/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
