[features]
seeds = false
[programs.localnet]
loki = "GxPZABaCGhe9MizXWLGy4Si2gwEt7FPUhjAiHkTWGp4u"

[programs.devnet]
loki = "GxPZABaCGhe9MizXWLGy4Si2gwEt7FPUhjAiHkTWGp4u"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/armariya/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
