[features]
seeds = true 

[programs.localnet]
solscatter = "78WNnu3fBhSDtt8mFzy49GrPGhybffqdZjqc9eLo8rX9"

[programs.devnet]
solscatter = "78WNnu3fBhSDtt8mFzy49GrPGhybffqdZjqc9eLo8rX9"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/armariya/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
