[features]
seeds = true

[programs.localnet]
solscatter = "GRbLgbgZoqGEwMoa7ExB1kBaFUQqcNmivF1GTyLniU7N"

[programs.devnet]
solscatter = "GRbLgbgZoqGEwMoa7ExB1kBaFUQqcNmivF1GTyLniU7N"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/Ariya.l/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.spec.ts"
